
services:
  pipeline:
    container_name: pipeline
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./src:/app
      - ./src/pipeline/Dados:/app/Dados
    working_dir: /app
    command: python main.py


