my_postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres   # <-- altere aqui
      user: dbt
      password: dbt
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
      keepalives_idle: 0