# ./flink/Dockerfile
FROM apache/flink:1.19.1-scala_2.12-java17

# Instala Python 3 + pip, utilitários necessários e cria alias "python"
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-venv \
        curl && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

# Baixa as dependências Hadoop AWS diretamente no container (evita binários gigantes no Git)
RUN set -eux; \
    mkdir -p /opt/flink/lib; \
    curl -fsSL -o /opt/flink/lib/hadoop-aws-3.3.6.jar \
        https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar; \
    curl -fsSL -o /opt/flink/lib/aws-java-sdk-bundle-1.12.262.jar \
        https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

# Instala a API Python do Flink na mesma versão do cluster e o driver do Postgres (para UDFs, se precisar)
RUN pip3 install --no-cache-dir apache-flink==1.19.1 psycopg2-binary

# Opcional: torna explícito o executável do cliente PyFlink
ENV PYFLINK_CLIENT_EXECUTABLE=python3
